### ISSUE TITLE
Images from video are of low quality

### ISSUE THREAD

**Issue by mittalharsh54** [bhuvnesh123/FFmpeg-Video-Editor-Android#13]
How can we get directly bitmap instead of saving them?

**Comment by bhuvnesh123** [comment]
Add `-q:v 1` to command to improve quality of images from video.You can select a video quality level with -q:v n,where n is a number from 1-31, with 1 being highest quality/largest filesize and 31 being the lowest quality/smallest filesize.

**Comment by mittalharsh54** [comment]
I want to generate the gif image from video of 3 secs, so it is possible with this?

**Comment by bhuvnesh123** [comment]
You can generate gif from video.For that go through ffmpeg docs.As generate gif is not part of my sample project discussing here in issues doesn't make sense.
