### ISSUE TITLE
New Logo/icon

### ISSUE THREAD

**Issue by desuto** [bhuvnesh123/FFmpeg-Video-Editor-Android#14]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, your logo on this project unattractive and writing is not neat . Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by bhuvnesh123** [comment]
Thanks,You're welcome to contribute!

**Comment by desuto** [comment]
I have designed the logo for FFmpeg Video Editor. And this is the result of design. what do you think?
If there's something you want to change, let me know.
![ffmpeg video editor](https://user-images.githubusercontent.com/39637790/40648818-86991e52-6359-11e8-985c-dc651149e5c4.png)

**Comment by bhuvnesh123** [comment]
That looks great!!

**Comment by desuto** [comment]
Hi @bhuvnesh123 I have uploaded all the files. You can get it in the link below.
https://drive.google.com/open?id=15_h55b2dhHbykzIx0-gV-QHhrpNcU0y_

and I have sent the pull requests. please check.

**Comment by bhuvnesh123** [comment]
Thanks a lott..Can you please check the link as it is not opening?Can you please change text "Ffmpeg" to "FFmpeg"?

**Comment by bhuvnesh123** [comment]
As editor consist of other options also except cutting video,is it is ideal to have icons just for cut and play in logo?Please think on that...However I'll pull your code once you change text

**Comment by desuto** [comment]
I've changed it. please check the pull requests

**Comment by bhuvnesh123** [comment]
I have pulled it..thanks

**Comment by bhuvnesh123** [comment]
You can share files at bhuvneshvarma123@gmail.com for app icon.

**Comment by desuto** [comment]
I use scissor and play icons because in general the video editing is by cutting some videos to make it look interesting while in watch. although a simple but cutting video app is a video editing app

You're welcome

**Comment by desuto** [comment]
yes. I will send it

**Comment by bhuvnesh123** [comment]
Okay..This project  has other features also like compressing video,reversing video,extracting image frames from video,extracting audio from video,add fade in fade out effect,create fast and slow motion video

**Comment by desuto** [comment]
yes. this is a great app :-)

**Comment by bhuvnesh123** [comment]
thanks..
