### ISSUE TITLE
unable to share edited videos

### ISSUE THREAD

**Issue by sagorahmed** [bhuvnesh123/FFmpeg-Video-Editor-Android#17]
#### Expected behavior
I expected that using the Share Video feature I will able to share edited files with some platforms.
#### Actual behavior
When I try to share my edited video through some apps. The apps are showing that "Couldn't Attach File".
#### How to reproduce
* Open the app and tap on "Upload Video" button and select a video.
* There are many features of this app, select one of them. Suppose you select "Cut Video".
* Then the cutting process will start and after the end of the process, Video Preview page will arrive.
* Then tap on "Share Video" button and select which platform you want to share your video and then notice the thing.
* App version: 3.1
* Operating system: Android 6.0.1
* Device: Samsung Galaxy A5 (2016)

#### Recording Of The Bug
![gif_image2.gif](https://cdn.steemitimages.com/DQmdR83w32sKeLSTzn6LHQJeSWHNNo7AhUT8RLi8HU86Zdd/gif_image2.gif)

**Comment by bhuvnesh123** [comment]
Thanks..The issue will be resolved in upcoming release

**Comment by bhuvnesh123** [comment]
[Fixed](https://play.google.com/store/apps/details?id=videoeditor.bhuvnesh.com.ffmpegvideoeditor)
