### ISSUE TITLE
Slideshow of PNG images cannot be played

### ISSUE THREAD

**Issue by neupanedipen** [bhuvnesh123/FFmpeg-Video-Editor-Android#18]
#### Expected behavior<br>
I should be able to create a slideshow with images in .PNG format.<br>
#### Actual behavior<br>
But the slideshow with .png format can not be played after trying to create one.<br>
#### How to reproduce<br>
1. Install the app from playstore.<br>
2. Launch the app.<br>
3. Go to &quot;Create Image Slideshow&quot; from left sliding menu. <br>
4. Pick some .png format images from your device. ( The screenshots are saved in .png format)<br>
5. Now click on &quot;Create Slideshow&quot;. Enter the duration between two images preview and continue. It will take some time and it will show &quot; Can&apos;t play this video&quot; at the end.<br>
* App Version: 3.1<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/Noy2bRThqyw

**Comment by bhuvnesh123** [comment]
Thanks..The issue will be resolved in upcoming release

**Comment by bhuvnesh123** [comment]
[Fixed](https://play.google.com/store/apps/details?id=videoeditor.bhuvnesh.com.ffmpegvideoeditor)
