### ISSUE TITLE
Update project with latest build

### ISSUE THREAD

**Issue by jmimohsin** [bhuvnesh123/FFmpeg-Video-Editor-Android#19]
Hi,

Please update project same as app and app is crashing when selecting image and swapping places.

Thanks.

**Comment by bhuvnesh123** [comment]
Hi,
As written in my project README "This repository contains sample project for an extended app on PlayStore" so as it's a sample it does not contain all the features that playstore app has!
Playstore App crash must be resolved now as it was updated many times after your comment!

Thanks
