### ISSUE TITLE
RangeSeekBar is not showing 

### ISSUE THREAD

**Issue by testingflexsin** [bhuvnesh123/FFmpeg-Video-Editor-Android#26]
RangeSeekBar is not showing in some devices like HTC Desire 820G Plus.

**Comment by corgiwooer** [comment]
Did you find the solution to it

**Comment by bhuvnesh123** [comment]
Add `rsb:barHeight="1dp"` to RangeSeekBar defined in activity_main.xml in case it's not showing!

**Comment by bhuvnesh123** [comment]
resolved...https://github.com/bhuvnesh123/FFmpeg-Video-Editor-Android/commit/4a86fa2ebd26ba79e59d927c1bc15a6767342481
