### ISSUE TITLE
After cutting video has low resolution, How can I fix it?

### ISSUE THREAD

**Issue by eraldhaka** [bhuvnesh123/FFmpeg-Video-Editor-Android#3]

**Comment by bhuvnesh123** [comment]
Remove  `-s 320x240` if you want to keep the resolution of original video.

**Comment by bhuvnesh123** [comment]
https://github.com/bhuvnesh123/FFmpeg-Video-Editor-Android/commit/55cae7b9f53486b3bd2b4452436156286fe1365a fixed

**Comment by eraldhaka** [comment]
Thank you for your answer.

**Comment by eraldhaka** [comment]
After removing -s 320x240 the video quality is still different than original video,
I have tried to change -s 320x240 with   -s 1280x720 , but still resolution is different than original video,
I have tried to use : 
{"-i", yourRealPath, "-ss", "" + startMs / 1000, "-t", "" + endMs / 1000, dest.getAbsolutePath()};  
but with this code the cutting process needs a lot of time, 
Can you please tell me right way for cutting with the quality of the original video in a short time?
Thank You

**Comment by bhuvnesh123** [comment]
Try using `"-acodec", "copy","-vcodec","copy"` to cut video without re-encoding it using copy codec for audio and video.This should keep the quality of original video.

**Comment by eraldhaka** [comment]
I have added your code, and the final code is: 
{"-i", yourRealPath, "-ss", "" + startMs / 1000,"-acodec", "copy","-vcodec","copy", "-t", "" + endMs / 1000, dest.getAbsolutePath()};
And it works great 
Thank You Man
