### ISSUE TITLE
how filters can be implemented using ffmpeg?

### ISSUE THREAD

**Issue by dabitdev** [bhuvnesh123/FFmpeg-Video-Editor-Android#34]
Hi @bhuvnesh123, this is a great open source project!!

Is there a good practice or known support of filters using ffmpeg?

Best,
David

**Comment by bhuvnesh123** [comment]
Please go through below links-
https://ffmpeg.org/ffmpeg-filters.html
https://trac.ffmpeg.org/wiki/FilteringGuide
