### ISSUE TITLE
Merge Audio And Video.

### ISSUE THREAD

**Issue by SuryaChundawat** [bhuvnesh123/FFmpeg-Video-Editor-Android#35]
Hi Bhuvnesh  can you please guide how to merge audio and video. As I can see in your play store app has this functionality. Thanks for help.

**Comment by bhuvnesh123** [comment]
For merging audio and video where input video file contains audio ,you can use below command-

`String command[] = {"-i",videoFileAbsolutePath,"-i",audioFileAbsolutePath, "-c:v", "copy", "-c:a", "aac","-map", "0:v:0", "-map", "1:a:0","-shortest", destinationAbsolutePath};`

For merging audio and video where input video file does not contain any audio stream ,you can use below command-

`String command[] = {"-i",videoFileAbsolutePath,"-i",audioFileAbsolutePath, "-c:v", "copy", "-c:a", "aac","-shortest", destinationAbsolutePath};`
