### ISSUE TITLE
Not working in android 10

### ISSUE THREAD

**Issue by gupta-aman1** [bhuvnesh123/FFmpeg-Video-Editor-Android#42]
After changing to target sdk to 29, unable to cut video
I have shared video 

https://user-images.githubusercontent.com/28038233/111664852-372a5780-8838-11eb-8b6c-ee00809b093e.mp4

https://user-images.githubusercontent.com/28038233/111664957-50cb9f00-8838-11eb-9961-3a50c6448048.mp4

**Comment by bhuvnesh123** [comment]
Without migrating the code, changing the target SDK versions will cause problem.
After increasing the target SDK version, you should update the code for selecting file from device storage .
