### ISSUE TITLE
Very slow performance

### ISSUE THREAD

**Issue by hardikJoshi123** [bhuvnesh123/FFmpeg-Video-Editor-Android#5]
Hello,

 I am using 1 second video for reversing video.. It takes around 3-4 minutes to process result video.. 
 What i am trying to achive : 

 I have 1 second video, now i want to display video forward and backward continously. 

Thanks!

**Comment by bhuvnesh123** [comment]
I have checked the reverse video functionality on multiple devices and it doesn't take more than 10 seconds to process 1 second video.Please make sure you are using same code as given in repository.If problem persists, you can share the video you are using at bhuvneshvarma123@gmail.com
