### ISSUE TITLE
How to merge two video?

### ISSUE THREAD

**Issue by hardikJoshi123** [bhuvnesh123/FFmpeg-Video-Editor-Android#6]
Hello,

 great library, video process is little slow.  Can you please provide a command for merge two videos? I have two video in sdcard, backward and forward. i want to merge both videos and create a new video which will look like 1 video with backward and forward. And i can upload it on server.

Thanks!

**Comment by bhuvnesh123** [comment]
Hi,
Check out Reverse Video section in my tutorial  in which I have given command for merging  segmented videos.Same command you can use for merging two videos.
