### ISSUE TITLE
How to cut video between seconds?

### ISSUE THREAD

**Issue by eraldhaka** [bhuvnesh123/FFmpeg-Video-Editor-Android#7]
For example :
startMs = 2.4 
endMs =  5.4
I have  tried this code:
String[] complexCommand = {"-i", yourRealPath, "-ss", "" + startMs, "-acodec", "copy", "-vcodec", "copy", "-t", "" + (endMs - startMs), dest.getAbsolutePath()};

But the cutting process happens with Full values (int values)... from "sec 2" to "sec 5"
Is there any way to cut video with "float values" ?
Thanks

**Comment by bhuvnesh123** [comment]
startMs and endMs are time values with unit milliseconds.So you can cut video between seconds.Like if you want to cut video between 2.4 second and 5.4 second than startMs should be equal to 2400 and endMs should be equal to 5400.

**Comment by eraldhaka** [comment]
Have you tried this before answering? Because I have tried and nothing happens...
