### ISSUE TITLE
How to improve reverse performance

### ISSUE THREAD

**Issue by anh-lt** [bhuvnesh123/FFmpeg-Video-Editor-Android#8]
Hi,

I am using your example application to reverse a video. The video has 9 seconds duration and its size is 14.3 MB but it takes about 15 minutes to process result video.

What should I do to improve the performance? 
Thanks.

**Comment by bhuvnesh123** [comment]
You can use "-preset", "ultrafast" to increase speed.

https://trac.ffmpeg.org/wiki/Encode/H.264

Ideally it should NOT take 15 minutes for a 9 second video and i have tested with different videos.If possible,you can share the video with which you are facing problem at bhuvneshvarma123@gmail.com
