### ISSUE TITLE
How to add filters to the video with the preview functionality

### ISSUE THREAD

**Issue by aloklearning** [bhuvnesh123/FFmpeg-Video-Editor-Android#9]
Your content is quiet good but I'm looking for a way out of adding the filters to the video. Since you have mentioned that your project has the adding filter functionality but no demonstration on your project. Please tell me how to do that. I've used surface view to first apply the filter to the videos at runtime but do not know how to save the file (merge the surface with the videos). Please suggest me some way out to reach to my solution.

**Comment by bhuvnesh123** [comment]
Where have i mentioned that my project has adding filter functionality?

**Comment by aloklearning** [comment]
I'm sorry you have not, but I wanna use your library and want to achieve to my solution. Is it possible. Thanks

**Comment by bhuvnesh123** [comment]
Please go through below links-
https://ffmpeg.org/ffmpeg-filters.html
https://trac.ffmpeg.org/wiki/FilteringGuide

**Comment by aloklearning** [comment]
I have read the documentation but with ffmpeg command lines we can apply and save the same filter at the same time. What I want to achieve is to apply the filters on the surface at the run time and then if like I want to save the video with the selected videos. That is why i'm searching a library or a way out to do the same. What i've achieved is I can now see the videos with the filters but do not know how to save the video with the selected filters. **I have used GLSurfaceView** for achieving the same
